<p class="smile"><t1>Welcome To FlyAero</t1>
<p class="line"></p>

		FlyAero virtual is now open! we can be found at www.flyaero.co.uk. We have a modern php system with a unique and attractive site. We are open to members of all abilities and we have staff who are always willing to help. We allow pilots to fly for any airline they like - Monarch, Thomas Cook, Thomson and Jet2 and if we don't have the airline you want, we will add it! We want to build a strong community base with a forum and a Teamspeak 3 server. Join today and be apart of the community.

<p class="line"></p>

<td><p class="smile"><t1>Lastest Pireps</t1>
<p class="line"></p></td>
<?php
        $flights = PIREPData::getRecentReportsByCount(5);                                                                      
        $string = "";
        foreach($flights as $flight)
        {       
                $string = $string.$flight->depicao.'+-+'.$flight->arricao.',+';
        }                                                                       
?>
<center>
<img src="http://www.gcmap.com/map?P=<?php echo $string ?>&amp;MS=bm&amp;MR=240&amp;MX=613x310&amp;PM=pemr:diamond7:red%2b%22%25I%22:red&amp;PC=%230000ff" /></center>
                          <div align="center">Maps generated by the <a href="http://www.gcmap.com/">Great Circle Mapper</a>&nbsp;- copyright © <a href="http://www.kls2.com/~karl/">Karl L. Swartz</a></div>

    <?php
$count = 5;
$pireps = PIREPData::getRecentReportsByCount($count);
?>
<table width="99%" cellpadding="2" cellspacing="1">
    <tr align="center">

      <th>Submited By</th>

      <th>Flight Number</th>

      <th>Departure</th>

      <th>Arrival</th>

      <th>Flight Time</th>

      <th>Aircraft</th>
      
      <th>Landing Rate</th>

      <th>Status</th>
		
      <?php

if(count($pireps) > 0)
{
  foreach ($pireps as $pirep)
  {
  {
        $pilotinfo = PilotData::getPilotData($pirep->pilotid);
        $pilotid = PilotData::getPilotCode($pilotinfo->code, $pilotinfo->pilotid);
} 
?>
      <tr>
        <td align="center"><?php echo $pilotinfo->firstname.' '.$pilotinfo->lastname; ?></td>
        </td>
        <td align="center"><?php echo $pirep->code.$pirep->flightnum; ?></td>
        <td align="center"><?php echo $pirep->depicao; ?></td>
        <td align="center"><?php echo $pirep->arricao; ?></td>
        <td align="center"><?php echo $pirep->flighttime; ?></td>
        <td align="center"><?php echo $pirep->aircraft; ?></td>
        <td align="center"><?php if($pirep->landingrate == '0') {echo 'Not recorded';} else {echo "{$pirep->landingrate} ft/min"; }?></td>
        <td align="center"><?php
                
                if($pirep->accepted == PIREP_ACCEPTED)
                        echo '<span style="color:#347C17"><strong>Accepted</strong></span>';
                elseif($pirep->accepted == PIREP_REJECTED)
                        echo '<span style="color:#FF0000"><strong>Rejected</strong></span>';
                elseif($pirep->accepted == PIREP_PENDING)
                        echo '<span style="color:#E56717"><strong>Approval Pending</strong></span>';
                elseif($pirep->accepted == PIREP_INPROGRESS)
                        echo '<span style="color:#whatever">Flight in Progress</span>';
                        ?>
        </td>
        <td>
      </tr>
      <?php
 }}
else
{
        echo '<tr><td align="center"><b>There are no recent flights!</b></td></tr>';
}
?>
     </tbody>
      </table>